import { c as create_ssr_component } from "../../../chunks/ssr.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<section id="main-banner-page" class="position-relative page-header work-header section-nav-smooth parallax" data-svelte-h="svelte-177y9zk"><div class="container"><div class="row shift-tole"><div class="col-lg-6 offset-lg-3"><div class="page-titles text-dark text-center padding"><h2 class="font-bold">همکاری با ما</h2> <h3 class="font-light py-3">ما اینجا هستیم</h3></div></div></div> <div class="gradient-bg title-wrap mt-n5"><div class="row"><div class="col-lg-12 col-md-12 whitecolor"><h3 class="float-end">همکاری با ما</h3> <ul class="breadcrumb top10 bottom10 float-start"><li class="breadcrumb-item hover-light"><a href="/">خانه</a></li> <li class="breadcrumb-item hover-light">همکاری با ما</li></ul></div></div></div></div></section>   <section id="stayconnect1" class="bglight position-relative padding noshadow"><div class="container whitebox"><div class="widget py-5"><div class="row"><div class="col-md-12 text-center wow fadeIn mt-n3" data-wow-delay="300ms" data-svelte-h="svelte-1to9b7m"><h2 class="heading bottom30 darkcolor font-light2 pt-1"><span class="font-normal">همکاری</span> با ما
                        <span class="divider-center"></span></h2></div> <div class="col-md-12 col-sm-12"><div class="heading-title wow fadeInUp" data-wow-delay="300ms"><form class="getin_form wow fadeInUp" data-wow-delay="400ms" action="https://formsubmit.co/6d3ef0f5cdfe71fc71a5ba8b89dacbc4" method="POST"><div class="row px-2"><div class="row justify-content-between text-left" data-svelte-h="svelte-3fn0z"><div class="form-group"><input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1"> <label class="form-check-label" for="جناب اقا">جناب اقا</label><br> <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1"> <label class="form-check-label" for="سرکار خانوم">سرکار خانوم</label></div> <div class="row justify-content-between text-left"><div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3">نام :<span class="text-danger">*</span></label> <input type="text" id="fname" name="نام" placeholder="" required></div> <div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3">نام
                                          خوانوادگی:
                                          <span class="text-danger">*</span></label> <input type="text" id="lname" name=" نام خانوادگی" placeholder="" required></div></div> </div><br> <hr> <div class="row justify-content-between text-left"><div class="form-group col-sm-4 flex-column d-flex" data-svelte-h="svelte-mhraoq"><label for="X" class="form-control-label px-3">تلفن ثابت
                                        :<span class="text-danger">*</span></label> <input type="text" id="تلفن ثابت" name="تلفن ثابت" placeholder="(به همراه پیش شماره)" minlength="10" maxlength="12" required></div> <div class="form-group col-sm-4 flex-column d-flex" data-svelte-h="svelte-1bal9x6"><label for="X" class="form-control-label px-3">شماره موبایل
                                        :<span class="text-danger">*</span></label> <input type="text" id="شماره موبایل" name="شماره موبایل" placeholder="" minlength="10" maxlength="12" required></div> <div class="form-group col-sm-4 flex-column d-flex"><label for="X" class="form-control-label px-3" data-svelte-h="svelte-rmg3nr">نوع مالکیت
                                        :<span class="text-danger">*</span></label> <select required class="custom-select form-group flex-column d-flex" id="inlineFormCustomSelectPref" style="padding: 8px 15px !important"><option selected value=" " data-svelte-h="svelte-17wemn9">انتخاب کنید</option><option value="مالک" data-svelte-h="svelte-2935ba">مالک</option><option value="استیجاری" data-svelte-h="svelte-8w7hl2">استیجاری</option></select></div> </div><br> <div class="row justify-content-between text-left"><div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3" data-svelte-h="svelte-9xi3nq">استان
                                        :<span class="text-danger">*</span></label> <select class="custom-select form-group flex-column d-flex" id="inlineFormCustomSelectPref" style="padding: 8px 15px !important"><option selected value=" " data-svelte-h="svelte-17wemn9">انتخاب کنید</option><option value="آذربایجان شرقی" data-svelte-h="svelte-604x0w">آذربایجان شرقی</option><option value="آذربایجان غربی" data-svelte-h="svelte-148vx2g">آذربایجان غربی</option><option value="اردبیل" data-svelte-h="svelte-1fr5rxg">اردبیل</option><option value="اصفهان" data-svelte-h="svelte-6cwfa0">اصفهان</option><option value="البرز" data-svelte-h="svelte-1jfv4w2">البرز</option><option value="ایلام" data-svelte-h="svelte-kuprao">ایلام</option><option value="بوشهر" data-svelte-h="svelte-1ek7f0u">بوشهر</option><option value="تهران" data-svelte-h="svelte-1nf95o0">تهران</option><option value="چهارمحال و بختیاری" data-svelte-h="svelte-1u1tys8">چهارمحال و بختیاری</option><option value="خراسان جنوبی" data-svelte-h="svelte-69pltg">خراسان جنوبی</option><option value="خراسان رضوی" data-svelte-h="svelte-dya1g8">خراسان رضوی</option><option value="خراسان شمالی" data-svelte-h="svelte-11f7b3k">خراسان شمالی</option><option value="خوزستان" data-svelte-h="svelte-1qdmzqe">خوزستان</option><option value="زنجان" data-svelte-h="svelte-hr2d6g">زنجان</option><option value="سمنان" data-svelte-h="svelte-1ippdmw">سمنان</option><option value="سیستان و بلوچستان" data-svelte-h="svelte-1jczqnk">سیستان و بلوچستان</option><option value="فارس" data-svelte-h="svelte-1xbh498">فارس</option><option value="قزوین" data-svelte-h="svelte-x7vprq">قزوین</option><option value="قم" data-svelte-h="svelte-1y261eg">قم</option><option value="کردستان" data-svelte-h="svelte-1m02z7g">کردستان</option><option value="کرمان" data-svelte-h="svelte-oqdaoi">کرمان</option><option value="کرمانشاه" data-svelte-h="svelte-1qb8tsk">کرمانشاه</option><option value="کهگیلویه و بویراحمد" data-svelte-h="svelte-p6qtgw">کهگیلویه و بویراحمد</option><option value="گلستان" data-svelte-h="svelte-1mcp71s">گلستان</option><option value="گیلان" data-svelte-h="svelte-i2s0u">گیلان</option><option value="لرستان" data-svelte-h="svelte-a23218">لرستان</option><option value="مازندران" data-svelte-h="svelte-1ptbmko">مازندران</option><option value="مرکزی" data-svelte-h="svelte-1gvef8k">مرکزی</option><option value="هرمزگان" data-svelte-h="svelte-hlj068">هرمزگان</option><option value="همدان" data-svelte-h="svelte-1gstf7m">همدان</option><option value="یزد" data-svelte-h="svelte-xodmsw">یزد</option></select></div> <div class="form-group col-sm-6 flex-column d-flex" data-svelte-h="svelte-1eogeaw"><label for="X" class="form-control-label px-3">شهر
                                        :<span class="text-danger">*</span></label> <input type="text" id="شهر محل نمایندگی" name="شهر محل نمایندگی" placeholder="" required></div> </div><br> <div class="row justify-content-between text-left" data-svelte-h="svelte-1ekd1vm"><div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3">آدرس کامل
                                        :</label> <input type="text" id="آدرس کامل" name="آدرس کامل" placeholder="بلوار / خیابان / کوچه / پلاک و ..."></div> <div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3">کد پستی
                                        :<span class="text-danger">*</span></label> <input type="text" id="کد پستی" name="کد پستی" placeholder="کد پستی ده رقمی" minlength="10" maxlength="10" required></div> </div><br> <div class="row justify-content-between text-left" data-svelte-h="svelte-f7euch"><div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3">آدرس ایمیل
                                        :<span class="text-danger">*</span></label> <input type="email" id="آدرس ایمیل" name="آدرس ایمیل" placeholder="" required></div> <div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3">وبسایت
                                        :</label> <input type="text" id="وبسایت" name="وبسایت" placeholder="www.example.ir"></div></div> <hr><br> <div class="row justify-content-between text-left" data-svelte-h="svelte-i6esar"><div class="form-group col-sm-4 flex-column d-flex"><label for="X" class="form-control-label px-3">نام واحد تجاری
                                        :<span class="text-danger">*</span></label> <input type="text" id="نام واحد تجاری" name="نام واحد تجاری" placeholder="" required></div> <div class="form-group col-sm-4 flex-column d-flex"><label for="X" class="form-control-label px-3">تاریخ تاسیس
                                        :</label> <input type="text" id="تاریخ تاسیس" name="تاریخ تاسیس" placeholder=""></div> <div class="form-group col-sm-4 flex-column d-flex"><label for="X" class="form-control-label px-3">زمینه فعالیت
                                        :<span class="text-danger">*</span></label> <input type="text" id="زمینه فعالیت" name="زمینه فعالیت" placeholder="" required></div> </div><br> <div class="row justify-content-between text-left" data-svelte-h="svelte-1llqqbs"><div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3">مشخصات سهامدارن/صاحبان شرکت با ذکر سمت، درصد سهم،تحصیلات:</label> <textarea name="مشخصات سهامدارن/صاحبان شرکت با ذکر سمت، درصد سهم،تحصیلات" class="form-control" id="مشخصات سهامدارن/صاحبان شرکت با ذکر سمت، درصد سهم،تحصیلات" rows="4"></textarea></div> <div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3">آیا از بدو
                                        تاسیس در محل فعلی فعالیت داشته اید؟:
                                      </label><textarea name="آیا از بدو تاسیس در محل فعلی فعالیت داشته اید؟" class="form-control" id="آیا از بدو تاسیس در محل فعلی فعالیت داشته اید؟" rows="4"></textarea></div></div> <hr><br> <div class="row justify-content-between text-left"><div class="form-group col-sm-6 flex-column d-flex" data-svelte-h="svelte-1teot2n"><label for="X" class="form-control-label px-3">شماره شناسنامه
                                        :</label> <input type="text" id="شماره شناسنامه" name="شماره شناسنامه" placeholder=""></div> <div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3" data-svelte-h="svelte-1djdtgw">استان محل تولد
                                        :</label> <select class="custom-select form-group flex-column d-flex" id="inlineFormCustomSelectPref" style="padding: 8px 15px !important"><option selected value=" " data-svelte-h="svelte-17wemn9">انتخاب کنید</option><option value="آذربایجان شرقی" data-svelte-h="svelte-604x0w">آذربایجان شرقی</option><option value="آذربایجان غربی" data-svelte-h="svelte-148vx2g">آذربایجان غربی</option><option value="اردبیل" data-svelte-h="svelte-1fr5rxg">اردبیل</option><option value="اصفهان" data-svelte-h="svelte-6cwfa0">اصفهان</option><option value="البرز" data-svelte-h="svelte-1jfv4w2">البرز</option><option value="ایلام" data-svelte-h="svelte-kuprao">ایلام</option><option value="بوشهر" data-svelte-h="svelte-1ek7f0u">بوشهر</option><option value="تهران" data-svelte-h="svelte-1nf95o0">تهران</option><option value="چهارمحال و بختیاری" data-svelte-h="svelte-1u1tys8">چهارمحال و بختیاری</option><option value="خراسان جنوبی" data-svelte-h="svelte-69pltg">خراسان جنوبی</option><option value="خراسان رضوی" data-svelte-h="svelte-dya1g8">خراسان رضوی</option><option value="خراسان شمالی" data-svelte-h="svelte-11f7b3k">خراسان شمالی</option><option value="خوزستان" data-svelte-h="svelte-1qdmzqe">خوزستان</option><option value="زنجان" data-svelte-h="svelte-hr2d6g">زنجان</option><option value="سمنان" data-svelte-h="svelte-1ippdmw">سمنان</option><option value="سیستان و بلوچستان" data-svelte-h="svelte-1jczqnk">سیستان و بلوچستان</option><option value="فارس" data-svelte-h="svelte-1xbh498">فارس</option><option value="قزوین" data-svelte-h="svelte-x7vprq">قزوین</option><option value="قم" data-svelte-h="svelte-1y261eg">قم</option><option value="کردستان" data-svelte-h="svelte-1m02z7g">کردستان</option><option value="کرمان" data-svelte-h="svelte-oqdaoi">کرمان</option><option value="کرمانشاه" data-svelte-h="svelte-1qb8tsk">کرمانشاه</option><option value="کهگیلویه و بویراحمد" data-svelte-h="svelte-p6qtgw">کهگیلویه و بویراحمد</option><option value="گلستان" data-svelte-h="svelte-1mcp71s">گلستان</option><option value="گیلان" data-svelte-h="svelte-i2s0u">گیلان</option><option value="لرستان" data-svelte-h="svelte-a23218">لرستان</option><option value="مازندران" data-svelte-h="svelte-1ptbmko">مازندران</option><option value="مرکزی" data-svelte-h="svelte-1gvef8k">مرکزی</option><option value="هرمزگان" data-svelte-h="svelte-hlj068">هرمزگان</option><option value="همدان" data-svelte-h="svelte-1gstf7m">همدان</option><option value="یزد" data-svelte-h="svelte-xodmsw">یزد</option></select></div> </div><br> <div class="row justify-content-between text-left"><div class="form-group col-sm-6 flex-column d-flex" data-svelte-h="svelte-y2gc71"><label for="X" class="form-control-label px-3">کد ملی
                                        :</label> <input type="text" id="کد ملی" name="کد ملی" placeholder=""></div> <div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3" data-svelte-h="svelte-1kbj10z">تحصیلات
                                        :</label> <select class="custom-select form-group flex-column d-flex" id="inlineFormCustomSelectPref" style="padding: 8px 15px !important"><option selected value=" " data-svelte-h="svelte-17wemn9">انتخاب کنید</option><option value="سیکل" data-svelte-h="svelte-1h0h5oc">سیکل</option><option value="دیپلم" data-svelte-h="svelte-wdahti">دیپلم</option><option value="کاردانی - فوق دیپلم" data-svelte-h="svelte-3uz334">کاردانی - فوق دیپلم</option><option value="کارشناسی - لیسانس" data-svelte-h="svelte-18dtil4">کارشناسی - لیسانس</option><option value="کارشناسی ارشد - فوق لیسانس" data-svelte-h="svelte-1qannbc">کارشناسی ارشد - فوق لیسانس</option><option value="دکتری" data-svelte-h="svelte-dteb5s">دکتری</option></select></div></div> <hr><br> <div class="row justify-content-between text-left" data-svelte-h="svelte-xyhexm"><div class="form-group col-sm-4 flex-column d-flex"><label for="X" class="form-control-label px-3">بانک
                                        :</label> <input type="text" id="بانک" name="بانک" placeholder=""></div> <div class="form-group col-sm-4 flex-column d-flex"><labe for="X" l class="form-control-label px-3">شعبه
                                        :</labe> <input type="text" id="شعبه" name="شعبه" placeholder=""></div> <div class="form-group col-sm-4 flex-column d-flex"><label for="X" class="form-control-label px-3">نوع حساب
                                        :</label> <input type="text" id="نوع حساب" name="نوع حساب" placeholder=""></div> </div><br> <div class="row justify-content-between text-left" data-svelte-h="svelte-1bylwgu"><div class="form-group col-sm-4 flex-column d-flex"><label for="X" class="form-control-label px-3">شماره تلفن
                                        بانک
                                        :</label> <input type="text" id="شماره تلفن بانک" name="شماره تلفن بانک" placeholder=""></div> <div class="form-group col-sm-4 flex-column d-flex"><label for="X" class="form-control-label px-3">شماره حساب
                                        :</label> <input type="text" id="شماره حساب" name="شماره حساب" placeholder=""></div> <div class="form-group col-sm-4 flex-column d-flex"><label for="X" class="form-control-label px-3">شماره یک برگ
                                        از دسته چک
                                        :</label> <input type="text" id="شماره یک برگ از دسته چک" name="شماره یک برگ از دسته چک" placeholder=""></div> </div><br> <div class="row justify-content-between text-left" data-svelte-h="svelte-zuuh4a"><div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3">سابقه فعالیت</label> <textarea name="سابقه فعالیت" class="form-control" id="سابقه فعالیت" rows="5"></textarea></div> <div class="form-group col-sm-6 flex-column d-flex"><label for="X" class="form-control-label px-3">آیا در زمینه
                                        فروش سایر برندهای موجود در بازار فعالیت دارید:</label> <textarea name="آیا در زمینه فروش سایر برندهای موجود در بازار فعالیت دارید:" class="form-control" id="آیا در زمینه فروش سایر برندهای موجود در بازار فعالیت دارید:" rows="4"></textarea></div></div> <br> <div class="row justify-content-end" data-svelte-h="svelte-1frq9h8"><div class="form-group col-sm-12"><button type="submit" class="btn-block btn-primary">ثبت
                                        اطلاعات</button></div> </div><br></div></form></div></div></div></div></div></section> `;
});
export {
  Page as default
};
